# COGS Resource Utilization Analysis

The script uses `Python` and its libraries to initiate data cleaning & pre-processing, analysis and visualization. Using time logs from the months of April, May and June, it gives a clear 
weekly utilization rate based on the time data

## 1. Data Cleaning and Pre-processing
At this point in time, the script loads the necessary libraries that it uses to clean, manipulate and plot the visualizations.

In [1]:
import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
import os

`Dash` is a popular python framework that allows its users to build interactive, web based dashboards. It can easly work with `plotly.express`

### 1.1 Loading files to script
The script utilizes `os.path.join()` to dynamically construct file paths that will be portable across the common operating systems when running it

In [2]:
relative_path = "timelogs"

april_logs = pd.read_csv(os.path.join(relative_path, "timelogs_april.csv"))
may_logs = pd.read_csv(os.path.join(relative_path, "timelogs_may.csv"))
june_logs = pd.read_csv(os.path.join(relative_path, "timelogs_june.csv"))

C:\Users\mukam\AppData\Local\Temp\ipykernel_5004\1006216092.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  april_logs = pd.read_csv(os.path.join(relative_path, "timelogs_april.csv"))

### 1.2 Combining logs into one data frame

In [3]:
time_logs = pd.concat([april_logs, may_logs, june_logs])

In [4]:
time_logs.describe()

                 Id   Logged Hours
count  1.185210e+05  118521.000000
mean   4.751382e+06       2.067043
std    4.637044e+04       2.041002
min    4.452832e+06       0.000000
25%    4.715635e+06       0.750000
50%    4.746476e+06       1.000000
75%    4.791899e+06       3.000000
max    4.835866e+06      17.500000

### 1.3 Confirming & converting column data types

In [5]:
print(time_logs.dtypes)

Id                              int64
Status                         object
Person > Department > Type     object
Person > Brand                 object
Location                       object
Project                        object
Bid Link                       object
Task                           object
Type                           object
Department                     object
Step                           object
Date                           object
Logged Hours                  float64
Start Time                     object
Stop Time                      object
Pay Period                     object
dtype: object

In [12]:
time_logs

,Id,Status,Person > Department > Type,Person > Brand,Location,Project,Bid Link,Task,Type,Department,Step,Date,Logged Hours,Start Time,Stop Time,Pay Period
0,4701614,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/09/2024,2.00,04/09/2024 14:00,04/09/2024 16:00,MT - PayPeriod 9 - 04/07/2024
1,4701615,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/11/2024,2.00,04/11/2024 14:00,04/11/2024 16:00,MT - PayPeriod 9 - 04/07/2024
2,4701616,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/10/2024,2.00,04/10/2024 14:00,04/10/2024 16:00,MT - PayPeriod 9 - 04/07/2024
3,4672203,sub,COGS,Folks,MT,ProjectK,PRK101,Animation,Worktime,Animation,ANM - Animation (Shot),04/02/2024,3.00,04/02/2024 14:00,04/02/2024 17:00,MT - PayPeriod 8 - 03/24/2024
4,4681659,sub,COGS,Folks,MT,Conrad,CRD999,Animation,Worktime,Layout,ANM - Animation (Shot),04/02/2024,2.00,04/02/2024 10:00,04/02/2024 12:00,MT - PayPeriod 8 - 03/24/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26145,4835862,NaN,non-artist COGS,Fuse,GA,FuseFX Admin,NaN,NaN,Meeting,CG Supervision,NaN,6/21/24,0.25,6/21/24 10:00,6/21/24 10:15,GA - PayPeriod 14 - 06/17/2024
26146,4835863,NaN,non-artist COGS,Fuse,GA,FuseFX Admin,NaN,NaN,Meal Break,CG Supervision,NaN,6/17/24,1.00,6/17/24 14:30,6/17/24 15:30,GA - PayPeriod 14 - 06/17/2024
26147,4835864,NaN,non-artist COGS,Fuse,GA,FuseFX Admin,NaN,NaN,Meal Break,CG Supervision,NaN,6/18/24,1.00,6/18/24 12:30,6/18/24 13:30,GA - PayPeriod 14 - 06/17/2024
26148,4835865,NaN,non-artist COGS,Fuse,GA,FuseFX Admin,NaN,NaN,Meal Break,CG Supervision,NaN,6/20/24,1.00,6/20/24 12:30,6/20/24 13:30,GA - PayPeriod 14 - 06/17/2024
26149,4835866,NaN,non-artist COGS,Fuse,GA,FuseFX Admin,NaN,NaN,Meal Break,CG Supervision,NaN,6/21/24,1.00,6/21/24 12:30,6/21/24 13:30,GA - PayPeriod 14 - 06/17/2024

In [14]:
# Identify rows with invalid date formats
invalid_dates = time_logs[~time_logs['Date'].str.match(r'\d{1,2}/\d{1,2}/\d{2}$')]
invalid_dates

,Id,Status,Person > Department > Type,Person > Brand,Location,Project,Bid Link,Task,Type,Department,Step,Date,Logged Hours,Start Time,Stop Time,Pay Period
0,4701614,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/09/2024,2.0,04/09/2024 14:00,04/09/2024 16:00,MT - PayPeriod 9 - 04/07/2024
1,4701615,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/11/2024,2.0,04/11/2024 14:00,04/11/2024 16:00,MT - PayPeriod 9 - 04/07/2024
2,4701616,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/10/2024,2.0,04/10/2024 14:00,04/10/2024 16:00,MT - PayPeriod 9 - 04/07/2024
3,4672203,sub,COGS,Folks,MT,ProjectK,PRK101,Animation,Worktime,Animation,ANM - Animation (Shot),04/02/2024,3.0,04/02/2024 14:00,04/02/2024 17:00,MT - PayPeriod 8 - 03/24/2024
4,4681659,sub,COGS,Folks,MT,Conrad,CRD999,Animation,Worktime,Layout,ANM - Animation (Shot),04/02/2024,2.0,04/02/2024 10:00,04/02/2024 12:00,MT - PayPeriod 8 - 03/24/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45924,4743142,NaN,SG&A,Folks,MT,Misc,NaN,NaN,Worktime,Marketing,NaN,05/03/2024,0.5,05/03/2024 09:00,05/03/2024 09:30,MT - PayPeriod 10 - 04/21/2024
45925,4743143,NaN,SG&A,Folks,MT,Misc,NaN,NaN,Worktime,Marketing,NaN,05/03/2024,0.5,05/03/2024 10:30,05/03/2024 11:00,MT - PayPeriod 10 - 04/21/2024
45926,4743144,NaN,SG&A,Folks,MT,Misc,NaN,NaN,Worktime,Marketing,NaN,05/03/2024,0.5,05/03/2024 11:30,05/03/2024 12:00,MT - PayPeriod 10 - 04/21/2024
45927,4743145,NaN,SG&A,Folks,MT,Misc,NaN,NaN,Worktime,Marketing,NaN,05/03/2024,2.0,05/03/2024 13:00,05/03/2024 15:00,MT - PayPeriod 10 - 04/21/2024
45928,4743146,NaN,SG&A,Folks,MT,Misc,NaN,NaN,Worktime,Marketing,NaN,05/03/2024,1.0,05/03/2024 17:00,05/03/2024 18:00,MT - PayPeriod 10 - 04/21/2024

There are 3 possible conversions that can be performed to enhance the analysis, optimize memory usage and performance.

#### 1.3.1 Categorical Columns

In [6]:
categorical_columns = ['Status', 'Person > Department > Type', 'Person > Brand', 
                       'Location', 'Project', 'Bid Link', 'Task', 'Type', 
                       'Department', 'Step', 'Pay Period']

for col in categorical_columns:
    time_logs[col] = time_logs[col].astype('category')

In [16]:
from datetime import datetime

def parse_date(date_str, formats):
    for fmt in formats:
        try:
            return datetime.strptime(date_str, fmt)
        except ValueError:
            pass
    return None

def sort_dates(date_strings, formats):
  return sorted(date_strings, key=lambda x: parse_date(x, formats))

date_strings = ["2024-01-01", "02/15/2023", "2023-12-25", "10-05-2022"]
date_formats = ["%Y-%m-%d", "%m/%d/%Y", "%Y-%m-%d", "%d-%m-%Y"]

sorted_dates = sort_dates(date_strings, date_formats)
print(sorted_dates)
# Expected Output: ['10-05-2022', '02/15/2023', '2023-12-25', '2024-01-01']

['10-05-2022', '02/15/2023', '2023-12-25', '2024-01-01']

#### 1.3.2 Date and Time Columns

In [17]:
time_logs['Date'] = pd.to_datetime(time_logs['Date'])

ValueError: time data "4/15/24" doesn't match format "%m/%d/%Y", at position 9. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
print(time_logs.dtypes)

Id                                     int64
Status                              category
Person > Department > Type          category
Person > Brand                      category
Location                            category
Project                             category
Bid Link                            category
Task                                category
Type                                category
Department                          category
Step                                category
Date                          datetime64[ns]
Logged Hours                         float64
Start Time                            object
Stop Time                             object
Pay Period                          category
dtype: object

In [8]:
time_logs['Start Time'] = pd.to_datetime(time_logs['Start Time'])
time_logs['Stop Time'] = pd.to_datetime(time_logs['Stop Time'])

ValueError: time data "4/15/24 8:30" doesn't match format "%m/%d/%Y %H:%M", at position 24. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
print(time_logs.dtypes)

Id                                     int64
Status                              category
Person > Department > Type          category
Person > Brand                      category
Location                            category
Project                             category
Bid Link                            category
Task                                category
Type                                category
Department                          category
Step                                category
Date                          datetime64[ns]
Logged Hours                         float64
Start Time                    datetime64[ns]
Stop Time                     datetime64[ns]
Pay Period                          category
dtype: object

#### 1.3.3 Logged Hours

In [ ]:
time_logs['Logged Hours'].fillna(0, inplace=True)

C:\Users\mukam\AppData\Local\Temp\ipykernel_3768\2980427867.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  time_logs['Logged Hours'].fillna(0, inplace=True)

### 1.4 Checking and handling missing values

In [ ]:
missing_values = time_logs.isnull().sum()
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
Id                                0
Status                        30730
Person > Department > Type        0
Person > Brand                    0
Location                          0
Project                           0
Bid Link                      50279
Task                          61324
Type                              0
Department                        0
Step                          60463
Date                              0
Logged Hours                      0
Start Time                        0
Stop Time                         0
Pay Period                     3323
dtype: int64

Due to the nature of the columns that are missing values, we will fill the with "Unknwown"

In [ ]:
#Since the script had converted 'status', 'bid link',etc into categorical columns, We have to insert 'unknown' as a category
# List of categorical columns with missing values
categorical_columns_with_missing = ['Status', 'Bid Link', 'Task', 'Step', 'Pay Period']


for col in categorical_columns_with_missing:
    # Only add the "Unknown" category if it's not already present
    if 'Unknown' not in time_logs[col].cat.categories:
        time_logs[col] = time_logs[col].cat.add_categories('Unknown')
    
    # Fill missing values with "Unknown"
    time_logs[col].fillna('Unknown', inplace=True)

# Check for any remaining missing values
print(time_logs.isnull().sum())

Id                            0
Status                        0
Person > Department > Type    0
Person > Brand                0
Location                      0
Project                       0
Bid Link                      0
Task                          0
Type                          0
Department                    0
Step                          0
Date                          0
Logged Hours                  0
Start Time                    0
Stop Time                     0
Pay Period                    0
dtype: int64

C:\Users\mukam\AppData\Local\Temp\ipykernel_3768\440604032.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  time_logs[col].fillna('Unknown', inplace=True)

## 2. Feature Engineering

From the data set, it can be assummed that the entries in the `logged hours` column are the differences between their corresponding start times and stop times. The script will establish if this is the case

In [ ]:
# calculating the difference and adding the result to the new 'duration' column
time_logs['Duration'] = (time_logs['Stop Time'] - time_logs['Start Time']).dt.total_seconds() / 3600


print(time_logs[['Start Time', 'Stop Time', 'Duration', 'Logged Hours']].head())

           Start Time           Stop Time  Duration  Logged Hours
0 2024-04-09 14:00:00 2024-04-09 16:00:00       2.0           2.0
1 2024-04-11 14:00:00 2024-04-11 16:00:00       2.0           2.0
2 2024-04-10 14:00:00 2024-04-10 16:00:00       2.0           2.0
3 2024-04-02 14:00:00 2024-04-02 17:00:00       3.0           3.0
4 2024-04-02 10:00:00 2024-04-02 12:00:00       2.0           2.0

###  2.1 Comparing 'Duration' to 'Logged Hours'

In [ ]:
# Check for discrepancies between Logged Hours and calculated Duration
discrepancies = time_logs[time_logs['Logged Hours'] != time_logs['Duration']]

# Get the total count of discrepancies
discrepancy_count = discrepancies.shape[0]

print(f"Total count of discrepancies: {discrepancy_count}")

Total count of discrepancies: 5516

Logged hours will be substituted with the new `duration` entires.

In [ ]:
time_logs['Logged Hours'] = time_logs['Duration']

### 2.2 Grouping and Aggregation

In order to prepare the data for visualization, the script groups the dataset depending on the categorical columns.

In [ ]:
# We are assuming the 
total_available_hours_per_week = 40
num_employees = time_logs['Id'].nunique()

num_employees

101175

#### 2.2.1 Weekly Aggregation

In [ ]:
# Add a Week column based on the Date
time_logs['Week'] = time_logs['Date'].dt.isocalendar().week

# Group by Week and Department, summing the Logged Hours
weekly_aggregation = time_logs.groupby(['Week', 'Department']).agg({
    'Logged Hours': 'sum'
}).reset_index()

# View a sample of the weekly aggregation
weekly_aggregation

C:\Users\mukam\AppData\Local\Temp\ipykernel_3768\2367801277.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weekly_aggregation = time_logs.groupby(['Week', 'Department']).agg({

     Week       Department  Logged Hours
0      13            Admin           0.0
1      13        Animation           0.0
2      13              Art           0.0
3      13            Asset           0.0
4      13        CG Artist           0.0
..    ...              ...           ...
475    27          Rigging          48.0
476    27      Supervision           8.0
477    27         Tracking          58.0
478    27   VFX Production         320.0
479    27  VFX Supervision         384.0

[480 rows x 3 columns]

In [ ]:
# Sort the weekly aggregation by Logged Hours in descending order
weekly_aggregation = weekly_aggregation.sort_values(by='Logged Hours', ascending=False)

# View the sorted aggregation (top departments by Logged Hours)
print(weekly_aggregation.head())

     Week  Department  Logged Hours
295    22  Compositor   7798.083333
167    18  Compositor   7758.616667
135    17  Compositor   4683.950000
327    23  Compositor   4602.716667
39     14  Compositor   4395.800000

In [ ]:
# Count the number of employees (Person) in each Department per Week
weekly_employee_count = time_logs.groupby(['Week', 'Department'])['Id'].nunique().reset_index(name='Employee Count')

# Merge the employee count into the weekly aggregation
weekly_aggregation = pd.merge(weekly_aggregation, weekly_employee_count, on=['Week', 'Department'])

# Calculate Total Available Hours per department per week (40 hours per employee)
weekly_aggregation['Total Available Hours'] = weekly_aggregation['Employee Count'] * 40

# Calculate Utilization Rate: (Logged Hours / Total Available Hours) * 100
weekly_aggregation['Utilization Rate'] = (weekly_aggregation['Logged Hours'] / weekly_aggregation['Total Available Hours']) * 100

# Sort by Utilization Rate in descending order
weekly_aggregation = weekly_aggregation.sort_values(by='Utilization Rate', ascending=False)

# View the final weekly aggregation with Utilization Rate
print(weekly_aggregation[['Week', 'Department', 'Logged Hours', 'Employee Count', 'Total Available Hours', 'Utilization Rate']].head())

     Week   Department  Logged Hours  Employee Count  Total Available Hours  \
339    18          Art          74.0               5                    200
359    22     Grooming          48.0               5                    200
408    18  Supervision          17.0               2                     80
365    26     Lighting          42.0               5                    200
225    22        Admin         289.5              35                   1400

     Utilization Rate
339         37.000000
359         24.000000
408         21.250000
365         21.000000
225         20.678571

C:\Users\mukam\AppData\Local\Temp\ipykernel_3768\4205837251.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weekly_employee_count = time_logs.groupby(['Week', 'Department'])['Id'].nunique().reset_index(name='Employee Count')

#### 2.2.2 Monthly Aggregation

In [ ]:
# Add a Month column based on the Date
time_logs['Month'] = time_logs['Date'].dt.to_period('M')

# Group by Month and Department, summing the Logged Hours
monthly_aggregation = time_logs.groupby(['Month', 'Department']).agg({
    'Logged Hours': 'sum'
}).reset_index()

# View a sample of the monthly aggregation


monthly_aggregation.sort_values(by='Logged Hours', ascending=False)

C:\Users\mukam\AppData\Local\Temp\ipykernel_3768\2799809396.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  monthly_aggregation = time_logs.groupby(['Month', 'Department']).agg({

       Month       Department  Logged Hours
71   2024-05       Compositor  24354.133333
39   2024-04       Compositor  20481.316667
95   2024-05  VFX Supervision  10019.933333
103  2024-06       Compositor   9213.400000
63   2024-04  VFX Supervision   8750.616667
..       ...              ...           ...
19   2024-03           Layout      0.000000
12   2024-03        Executive      0.000000
60   2024-04      Supervision      0.000000
132  2024-07        CG Artist      0.000000
154  2024-07        Reception      0.000000

[160 rows x 3 columns]

In [ ]:
# Count the number of unique employees (Person) in each Department per Month
monthly_employee_count = time_logs.groupby(['Month', 'Department'])['Id'].nunique().reset_index(name='Employee Count')

# Merge the employee count into the monthly aggregation
monthly_aggregation = pd.merge(monthly_aggregation, monthly_employee_count, on=['Month', 'Department'])

# View a sample of the merged data with employee count
monthly_aggregation.sort_values(by='Logged Hours', ascending=False)

C:\Users\mukam\AppData\Local\Temp\ipykernel_3768\3316275876.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  monthly_employee_count = time_logs.groupby(['Month', 'Department'])['Id'].nunique().reset_index(name='Employee Count')

       Month       Department  Logged Hours  Employee Count
71   2024-05       Compositor  24354.133333            9228
39   2024-04       Compositor  20481.316667           10052
95   2024-05  VFX Supervision  10019.933333            4397
103  2024-06       Compositor   9213.400000            4304
63   2024-04  VFX Supervision   8750.616667            4367
..       ...              ...           ...             ...
19   2024-03           Layout      0.000000               0
12   2024-03        Executive      0.000000               0
60   2024-04      Supervision      0.000000               0
132  2024-07        CG Artist      0.000000               0
154  2024-07        Reception      0.000000               0

[160 rows x 4 columns]

In [ ]:
# Calculate Total Available Hours per department per month (160 hours per employee)
monthly_aggregation['Total Available Hours'] = monthly_aggregation['Employee Count'] * 160

# Calculate Utilization Rate: (Logged Hours / Total Available Hours) * 100
monthly_aggregation['Utilization Rate'] = (monthly_aggregation['Logged Hours'] / monthly_aggregation['Total Available Hours']) * 100

# View the final monthly aggregation with Utilization Rate
print(monthly_aggregation[['Month', 'Department', 'Logged Hours', 'Employee Count', 'Total Available Hours', 'Utilization Rate']].head())

     Month Department  Logged Hours  Employee Count  Total Available Hours  \
0  2024-03      Admin           0.0               0                      0
1  2024-03  Animation           0.0               0                      0
2  2024-03        Art           0.0               0                      0
3  2024-03      Asset           0.0               0                      0
4  2024-03  CG Artist           0.0               0                      0

   Utilization Rate
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN

In [ ]:
# Sort by Utilization Rate in descending order (highest utilization at the top)
monthly_aggregation_sorted = monthly_aggregation.sort_values(by='Utilization Rate', ascending=False)

# View a sample of the sorted data
print(monthly_aggregation_sorted.head())

       Month              Department  Logged Hours  Employee Count  \
152  2024-07   Production Management          64.0               8
151  2024-07  Pipeline & Development         200.0              25
156  2024-07             Supervision           8.0               1
158  2024-07          VFX Production         320.0              40
153  2024-07               Real Time          16.0               2

     Total Available Hours  Utilization Rate
152                   1280               5.0
151                   4000               5.0
156                    160               5.0
158                   6400               5.0
153                    320               5.0

In [ ]:
print(monthly_aggregation_sorted.columns)

Index(['Month', 'Department', 'Logged Hours', 'Employee Count',
       'Total Available Hours', 'Utilization Rate'],
      dtype='object')

In [ ]:
weekly_aggregation.columns

Index(['Week', 'Department', 'Logged Hours', 'Employee Count',
       'Total Available Hours', 'Utilization Rate'],
      dtype='object')

## 3. Visualization

In [ ]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd

# Sample data (replace 'weekly_aggregation' with your DataFrame)
# weekly_aggregation is your DataFrame after processing

# Initialize the Dash app
app = dash.Dash(__name__)

# Custom CSS styles for rounded outlines and box shadows
box_style = {
    'padding': '20px', 
    'margin': '10px',
    'box-shadow': '0 4px 8px rgba(0, 0, 0, 0.1)',
    'border-radius': '10px',
    'background-color': 'white',
    'border': '1px solid #ddd'
}

score_card_style = {
    'text-align': 'center',
    'padding': '20px',
    'margin': '10px',
    'box-shadow': '0 4px 8px rgba(0, 0, 0, 0.1)',
    'border-radius': '10px',
    'background-color': 'white',
    'border': '1px solid #ddd',
}

score_value_style = {
    'font-size': '24px',
    'font-weight': 'bold',
    'color': '#007BFF'  # Blue color for emphasis
}

# Dashboard Layout
app.layout = html.Div([
    html.Div([
        html.H1('COGS Utilization Analysis', style={'text-align': 'center', 'padding': '20px'}),
    ], style={**box_style, 'text-align': 'center'}),  # Title box shadow and rounded

    # Filters
    html.Div([
        html.Div([
            html.Label('Department'),
            dcc.Dropdown(
                id='department-dropdown',
                options=[{'label': 'Select All', 'value': 'ALL'}] + [{'label': dept, 'value': dept} for dept in weekly_aggregation['Department'].unique()],
                value='ALL',
                clearable=False,
                style={'width': '100%'}
            ),
        ], style={**box_style, 'width': '45%', 'display': 'inline-block'}),

        html.Div([
            html.Label('Week'),
            dcc.Dropdown(
                id='week-dropdown',
                options=[{'label': 'Select All', 'value': 'ALL'}] + [{'label': str(week), 'value': week} for week in weekly_aggregation['Week'].unique()],
                value='ALL',
                clearable=False,
                style={'width': '100%'}
            ),
        ], style={**box_style, 'width': '45%', 'display': 'inline-block'})
    ], style={'padding': '20px', 'display': 'flex', 'justify-content': 'space-around'}),

    # Scorecards
    html.Div([
        html.Div([
            html.H4("Average Work Hours/Week", style={'text-align': 'center'}),
            html.Div(id='avg-hours-week', style=score_value_style),
        ], style=score_card_style),

        html.Div([
            html.H4("Average Utilization Rate", style={'text-align': 'center'}),
            html.Div(id='avg-util-rate', style=score_value_style),
        ], style=score_card_style),

        html.Div([
            html.H4("Total Hours Worked", style={'text-align': 'center'}),
            html.Div(id='total-hours', style=score_value_style),
        ], style=score_card_style)
    ], style={'display': 'flex', 'justify-content': 'space-around', 'padding': '20px'}),

    # Second Section: Bar chart and Column chart side by side
    html.Div([
        html.Div([
            dcc.Graph(id='bar-graph')
        ], style={**box_style, 'width': '50%', 'display': 'inline-block'}),
        html.Div([
            dcc.Graph(id='column-graph')
        ], style={**box_style, 'width': '50%', 'display': 'inline-block'})
    ], style={'padding': '10px', 'display': 'flex', 'justify-content': 'space-around'}),

    # Third Section: Table and Pie chart side by side
    html.Div([
        html.Div([
            html.H4('Top 10 Departments by Utilization Rate', style={'text-align': 'center'}),
            html.Table(id='top-departments-table', style={'width': '100%', 'border': '1px solid #ccc'}),
        ], style={**box_style, 'width': '50%', 'display': 'inline-block', 'background-color': '#f9f9f9'}),
        html.Div([
            dcc.Graph(id='pie-chart')
        ], style={**box_style, 'width': '50%', 'display': 'inline-block'})
    ], style={'padding': '10px', 'display': 'flex', 'justify-content': 'space-around'})
], style={'background-color': '#f9f9f9', 'padding': '20px'})

# Callback to update scorecards, graphs, and table
@app.callback(
    [Output('avg-hours-week', 'children'),
     Output('avg-util-rate', 'children'),
     Output('total-hours', 'children'),
     Output('bar-graph', 'figure'),
     Output('column-graph', 'figure'),
     Output('top-departments-table', 'children'),
     Output('pie-chart', 'figure')],
    [Input('department-dropdown', 'value'),
     Input('week-dropdown', 'value')]
)
def update_dashboard(selected_department, selected_week):
    # Filter data by week (and department if not 'ALL')
    if selected_week == 'ALL':
        filtered_data_week = weekly_aggregation
    else:
        filtered_data_week = weekly_aggregation[weekly_aggregation['Week'] == selected_week]

    if selected_department == 'ALL':
        filtered_data_dept = filtered_data_week
    else:
        filtered_data_dept = filtered_data_week[filtered_data_week['Department'] == selected_department]

    # Check if filtered data is empty
    if filtered_data_dept.empty or filtered_data_week.empty:
        return (
            "No data available",
            "No data available",
            "No data available",
            {}, {}, [html.Tr([html.Td("No data available")])], {}
        )

    # Calculate key metrics for the selected department or all departments
    avg_hours_week = filtered_data_dept['Logged Hours'].mean()
    avg_util_rate = filtered_data_dept['Utilization Rate'].mean()
    total_hours = filtered_data_dept['Logged Hours'].sum()

    # Format numbers for scorecards
    avg_hours_week_text = f"{avg_hours_week:.2f}"
    avg_util_rate_text = f"{avg_util_rate:.2f}%"
    total_hours_text = f"{total_hours:.2f}"

    # Bar graph: Utilization rate per department (using data filtered by week)
    bar_fig = px.bar(
        filtered_data_week,
        x='Department',
        y='Utilization Rate',
        title='Utilization Rate by Department'
    )

    # Column chart: Total logged hours per department (using data filtered by week)
    column_fig = px.bar(
        filtered_data_week,
        x='Department',
        y='Logged Hours',
        title='Total Logged Hours by Department'
    )

    # Table: Top 10 departments by utilization rate (using data filtered by week)
    top_departments = filtered_data_week.nlargest(10, 'Utilization Rate')[['Department', 'Utilization Rate']]
    
    # Table rows with light blue banded style
    table_rows = [
        html.Tr([html.Th('Department'), html.Th('Utilization Rate')], style={'background-color': '#e6f7ff'})
    ]
    for i, (_, row) in enumerate(top_departments.iterrows()):
        row_color = '#f2f9ff' if i % 2 == 0 else '#ffffff'
        table_rows.append(html.Tr([
            html.Td(row['Department']),
            html.Td(f"{row['Utilization Rate']:.2f}%")
        ], style={'background-color': row_color}))

    # Pie chart: Logged hours vs. unutilized hours for the selected department
    total_logged_hours = filtered_data_dept['Logged Hours'].sum()
    total_available_hours = filtered_data_dept['Employee Count'].sum() * 40  # Assuming 40 hours/week
    unutilized_hours = total_available_hours - total_logged_hours
    pie_fig = px.pie(
        values=[total_logged_hours, unutilized_hours],
        names=['Logged Hours', 'Unutilized Hours'],
        title='Logged vs Unutilized Hours'
    )

    return avg_hours_week_text, avg_util_rate_text, total_hours_text, bar_fig, column_fig, table_rows, pie_fig

# Run the Dash app and open in the browser
if __name__ == '__main__':
    app.run_server(debug=True, use_reloader=False)