# COGS Resource Utilization Analysis

The script uses `Python` and its libraries to initiate data cleaning & pre-processing, analysis and visualization. Using time logs from the months of April, May and June, it gives a clear 
weekly utilization rate based on the time data

## 1. Data Cleaning and Pre-processing
At this point in time, the script loads the necessary libraries that it uses to clean, manipulate and plot the visualizations.

In [143]:
import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html
from dash.dependencies import Input, Output
import os

`Dash` is a popular python framework that allows its users to build interactive, web based dashboards. It can easly work with `plotly.express`

### 1.1 Loading files to script
The script utilizes `os.path.join()` to dynamically construct file paths that will be portable across the common operating systems when running it

In [144]:
relative_path = "timelogs"

april_logs = pd.read_csv(os.path.join(relative_path, "timelogs_april.csv"))
may_logs = pd.read_csv(os.path.join(relative_path, "timelogs_may.csv"))
june_logs = pd.read_csv(os.path.join(relative_path, "timelogs_june.csv"))

C:\Users\mukam\AppData\Local\Temp\ipykernel_13308\1006216092.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  april_logs = pd.read_csv(os.path.join(relative_path, "timelogs_april.csv"))

### 1.2. Column Profiling

In [145]:
print('April\'s shape', april_logs.shape)
april_logs.info()
april_logs.head(5)

April's shape (45939, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45939 entries, 0 to 45938
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id                          45939 non-null  int64
 1   Status                      35014 non-null  object
 2   Person > Department > Type  45939 non-null  object
 3   Person > Brand              45939 non-null  object
 4   Location                    45939 non-null  object
 5   Project                     45939 non-null  object
 6   Bid Link                    27435 non-null  object
 7   Task                        23215 non-null  object
 8   Type                        45939 non-null  object
 9   Department                  45939 non-null  object
 10  Step                        23626 non-null  object
 11  Date                        45939 non-null  object
 12  Logged Hours                45939 non-null  float64
 13  Start Time                  45939 non-null  object
 14  Stop Time                   45939 non-null  object
 15  Pay Period                  45130 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 5.6+ MB

,Id,Status,Person > Department > Type,Person > Brand,Location,Project,Bid Link,Task,Type,Department,Step,Date,Logged Hours,Start Time,Stop Time,Pay Period
0,4701614,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/09/2024,2.0,04/09/2024 14:00,04/09/2024 16:00,MT - PayPeriod 9 - 04/07/2024
1,4701615,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/11/2024,2.0,04/11/2024 14:00,04/11/2024 16:00,MT - PayPeriod 9 - 04/07/2024
2,4701616,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/10/2024,2.0,04/10/2024 14:00,04/10/2024 16:00,MT - PayPeriod 9 - 04/07/2024
3,4672203,sub,COGS,Folks,MT,ProjectK,PRK101,Animation,Worktime,Animation,ANM - Animation (Shot),04/02/2024,3.0,04/02/2024 14:00,04/02/2024 17:00,MT - PayPeriod 8 - 03/24/2024
4,4681659,sub,COGS,Folks,MT,Conrad,CRD999,Animation,Worktime,Layout,ANM - Animation (Shot),04/02/2024,2.0,04/02/2024 10:00,04/02/2024 12:00,MT - PayPeriod 8 - 03/24/2024

In [146]:
print('May\'s shape',may_logs.shape)
may_logs.info()
may_logs.head(5)

May's shape (46432, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46432 entries, 0 to 46431
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id                          46432 non-null  int64
 1   Status                      34038 non-null  object
 2   Person > Department > Type  46432 non-null  object
 3   Person > Brand              46432 non-null  object
 4   Location                    46432 non-null  object
 5   Project                     46432 non-null  object
 6   Bid Link                    26325 non-null  object
 7   Task                        21894 non-null  object
 8   Type                        46432 non-null  object
 9   Department                  46432 non-null  object
 10  Step                        22159 non-null  object
 11  Date                        46432 non-null  object
 12  Logged Hours                46432 non-null  float64
 13  Start Time                  46432 non-null  object
 14  Stop Time                   46432 non-null  object
 15  Pay Period                  44885 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 5.7+ MB

,Id,Status,Person > Department > Type,Person > Brand,Location,Project,Bid Link,Task,Type,Department,Step,Date,Logged Hours,Start Time,Stop Time,Pay Period
0,4724705,sub,SG&A,Fuse,LA,FolksUnitTests,FUT789,NaN,Worktime,Pipeline & Development,CMP - Compositing (Shot),4/25/24,1.5,4/26/24 1:30,4/26/24 3:00,LA - PayPeriod 10 - 04/22/2024
1,4727152,sub,non-artist COGS,Folks,BO,PeterPan,PP100,Supervisor,Worktime,Composite Supervision,SUP - Supervisor (Episode),4/25/24,1.0,4/26/24 0:00,4/26/24 1:00,BO - PayPeriod 8 - 04/16/2024
2,4740999,sub,SG&A,Fuse,BC,FuseFX Admin,NaN,NaN,Worktime,Information Technology,NaN,4/25/24,0.5,4/26/24 0:30,4/26/24 1:00,BC - PayPeriod 10 - 04/21/2024
3,4741274,sub,non-artist COGS,Fuse,LA,Monster,MTR201,Producer,Worktime,VFX Production,PRO - Producer (Episode),4/25/24,2.5,4/26/24 0:30,4/26/24 3:00,LA - PayPeriod 10 - 04/22/2024
4,4745246,sub,non-artist COGS,Fuse,LA,Nuremberg,NUR100,Supervisor,Worktime,VFX Supervision,SUP - Supervisor (Episode),4/25/24,1.0,4/26/24 2:00,4/26/24 3:00,LA - PayPeriod 10 - 04/22/2024

In [147]:
june_logs.info()
print('June\'s Shape', june_logs.shape)
june_logs.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26150 entries, 0 to 26149
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id                          26150 non-null  int64
 1   Status                      18739 non-null  object
 2   Person > Department > Type  26150 non-null  object
 3   Person > Brand              26150 non-null  object
 4   Location                    26150 non-null  object
 5   Project                     26150 non-null  object
 6   Bid Link                    14482 non-null  object
 7   Task                        12088 non-null  object
 8   Type                        26150 non-null  object
 9   Department                  26150 non-null  object
 10  Step                        12273 non-null  object
 11  Date                        26150 non-null  object
 12  Logged Hours                26150 non-null  float64
 13  Start Time                  26150 non-null  object
 14  Stop Time                   26150 non-null  object
 15  Pay Period                  25183 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 3.2+ MB
June's Shape (26150, 16)

,Id,Status,Person > Department > Type,Person > Brand,Location,Project,Bid Link,Task,Type,Department,Step,Date,Logged Hours,Start Time,Stop Time,Pay Period
0,4833641,sub,COGS,Folks,TO,HotFrosty,HF100,Anim,Worktime,Animation,ANM - Animation (Shot),6/17/24,2.0,6/17/24 12:30,6/17/24 14:30,TO - PayPeriod 14 - 06/16/2024
1,4834898,sub,COGS,Folks,BO,Verne,JV300,Anim,Worktime,Animation,ANM - Animation (Asset),6/12/24,4.0,6/12/24 10:00,6/12/24 14:00,BO - PayPeriod 11 - 06/01/2024
2,4834899,sub,COGS,Folks,BO,Verne,JV300,Anim,Worktime,Animation,ANM - Animation (Asset),6/13/24,4.0,6/13/24 10:00,6/13/24 14:00,BO - PayPeriod 11 - 06/01/2024
3,4834900,sub,COGS,Folks,BO,Verne,JV300,Anim,Worktime,Animation,ANM - Animation (Asset),6/14/24,4.0,6/14/24 10:00,6/14/24 14:00,BO - PayPeriod 11 - 06/01/2024
4,4834902,sub,COGS,Folks,BO,Verne,JV300,Anim,Worktime,Animation,ANM - Animation (Asset),6/12/24,5.0,6/12/24 15:00,6/12/24 20:00,BO - PayPeriod 11 - 06/01/2024

Since all the DataFrames are of the shape and the order of columns are the same, the next step is to combine them into one DataFrame, `combined_time_logs`

### 1.3 Combining logs into one data frame

In [148]:
combined_time_logs = pd.concat([april_logs, may_logs, june_logs])
print('Combined shape:', combined_time_logs.shape)

combined_time_logs.info()
combined_time_logs.head()

Combined shape: (118521, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 118521 entries, 0 to 26149
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Id                          118521 non-null  int64
 1   Status                      87791 non-null   object
 2   Person > Department > Type  118521 non-null  object
 3   Person > Brand              118521 non-null  object
 4   Location                    118521 non-null  object
 5   Project                     118521 non-null  object
 6   Bid Link                    68242 non-null   object
 7   Task                        57197 non-null   object
 8   Type                        118521 non-null  object
 9   Department                  118521 non-null  object
 10  Step                        58058 non-null   object
 11  Date                        118521 non-null  object
 12  Logged Hours                118521 non-null  float64
 13  Start Time                  118521 non-null  object
 14  Stop Time                   118521 non-null  object
 15  Pay Period                  115198 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 15.4+ MB

,Id,Status,Person > Department > Type,Person > Brand,Location,Project,Bid Link,Task,Type,Department,Step,Date,Logged Hours,Start Time,Stop Time,Pay Period
0,4701614,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/09/2024,2.0,04/09/2024 14:00,04/09/2024 16:00,MT - PayPeriod 9 - 04/07/2024
1,4701615,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/11/2024,2.0,04/11/2024 14:00,04/11/2024 16:00,MT - PayPeriod 9 - 04/07/2024
2,4701616,sub,COGS,Folks,MT,RND,RND100,Anim,Worktime,Animation,ANM - Animation (Asset),04/10/2024,2.0,04/10/2024 14:00,04/10/2024 16:00,MT - PayPeriod 9 - 04/07/2024
3,4672203,sub,COGS,Folks,MT,ProjectK,PRK101,Animation,Worktime,Animation,ANM - Animation (Shot),04/02/2024,3.0,04/02/2024 14:00,04/02/2024 17:00,MT - PayPeriod 8 - 03/24/2024
4,4681659,sub,COGS,Folks,MT,Conrad,CRD999,Animation,Worktime,Layout,ANM - Animation (Shot),04/02/2024,2.0,04/02/2024 10:00,04/02/2024 12:00,MT - PayPeriod 8 - 03/24/2024

### 1.4 Review Data Types of the columns

Firstly, in order to preserve the original data set , the code will create a copy of the dataframe , `copy_combined_time_logs`

In [149]:
copy_combined_time_logs = combined_time_logs.copy()

Check the data types of the columns

In [150]:
print(copy_combined_time_logs.shape)
copy_combined_time_logs.info()

(118521, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 118521 entries, 0 to 26149
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Id                          118521 non-null  int64
 1   Status                      87791 non-null   object
 2   Person > Department > Type  118521 non-null  object
 3   Person > Brand              118521 non-null  object
 4   Location                    118521 non-null  object
 5   Project                     118521 non-null  object
 6   Bid Link                    68242 non-null   object
 7   Task                        57197 non-null   object
 8   Type                        118521 non-null  object
 9   Department                  118521 non-null  object
 10  Step                        58058 non-null   object
 11  Date                        118521 non-null  object
 12  Logged Hours                118521 non-null  float64
 13  Start Time                  118521 non-null  object
 14  Stop Time                   118521 non-null  object
 15  Pay Period                  115198 non-null  object
dtypes: float64(1), int64(1), object(14)
memory usage: 15.4+ MB

#### `Date` Column

In [151]:
copy_combined_time_logs['Date'] = pd.to_datetime(copy_combined_time_logs['Date'])

ValueError: time data "4/15/24" doesn't match format "%m/%d/%Y", at position 9. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

The above error is with regards to the attempted Datetime conversion we tried to effect in the above cell. The function `pd.to_datetime` is expecting a 'm/d/Y in the objects. The capital Y refers to the year in full, '2024'. Even though the `head()` function on the `combined_time_logs` shows that the dates in the `Date` column are in the format expected, '04/02/2024' some of the dates have the short year '4/2/24'.

Performing and in depth review of the data types in the column `Date`

In [152]:
copy_combined_time_logs['Date'].apply(type).value_counts()

Date
<class 'str'>    118521
Name: count, dtype: int64

In [153]:
copy_combined_time_logs['Date'].str.len().value_counts()

Date
7     72054
10    23706
6     22761
Name: count, dtype: int64

The source data has inconsistencies in how the dates have been entered. The first bucket i.e  dates with a length of 6 are in the format of m/d/y, the second bucker(7) are formated as m/dd/y while the last bucket (10) are in the format m/d/Y - Y capitalized means the year in full

In [154]:
copy_combined_time_logs.loc[copy_combined_time_logs['Date'].str.len() == 6, 'Date'].head(10)

5799    5/1/24
5800    5/1/24
5801    5/1/24
5802    5/1/24
5803    5/1/24
5804    5/1/24
5805    5/1/24
5806    5/1/24
5807    5/1/24
5808    5/1/24
Name: Date, dtype: object

In [155]:
copy_combined_time_logs.loc[copy_combined_time_logs['Date'].str.len() == 7, 'Date'].head(10)

25    4/15/24
26    4/19/24
27    4/19/24
28    4/15/24
29    4/16/24
30    4/18/24
31    4/22/24
32    4/24/24
33    4/26/24
34    4/26/24
Name: Date, dtype: object

In [156]:

copy_combined_time_logs.loc[copy_combined_time_logs['Date'].str.len() == 10, 'Date'].head(10)

0    04/09/2024
1    04/11/2024
2    04/10/2024
3    04/02/2024
4    04/02/2024
5    04/02/2024
6    04/03/2024
7    04/02/2024
8    04/04/2024
9    04/03/2024
Name: Date, dtype: object

To avoid errors associated with inferencing with `copy_combined_time_logs['Date'] = pd.to_datetime(copy_combined_time_logs['Date'])` as the code output, the next steps will involve updating the `Date` column in their various bucket to allow for a more a controlled approached.

In [157]:
# This is to remove any leading or trailing spaces in the 'Date' column
copy_combined_time_logs['Date'] = (copy_combined_time_logs['Date']
    .astype(str)
    .str.strip()
)

In [159]:
# Creating masks for different lengths of the 'Date' strings
mask_6  = copy_combined_time_logs['Date'].str.len() == 6
mask_7  = copy_combined_time_logs['Date'].str.len() == 7
mask_10 = copy_combined_time_logs['Date'].str.len() == 10

In [160]:
copy_combined_time_logs.loc[mask_6, 'Date'] = pd.to_datetime(
    copy_combined_time_logs.loc[mask_6, 'Date'],
    format='%m/%d/%y',
    errors='coerce'
)

copy_combined_time_logs.loc[mask_7, 'Date'] = pd.to_datetime(
    copy_combined_time_logs.loc[mask_7, 'Date'],
    format='%m/%d/%y',
    errors='coerce'
)

copy_combined_time_logs.loc[mask_10, 'Date'] = pd.to_datetime(
    copy_combined_time_logs.loc[mask_10, 'Date'],
    format='%m/%d/%Y',
    errors='coerce'
)

In [161]:
copy_combined_time_logs['Date'] = pd.to_datetime(copy_combined_time_logs['Date'])

In [162]:
copy_combined_time_logs['Date'].isna().sum()

np.int64(0)

Confirming `Date` data type and no null exists

In [164]:
copy_combined_time_logs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118521 entries, 0 to 26149
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Id                          118521 non-null  int64
 1   Status                      87791 non-null   object
 2   Person > Department > Type  118521 non-null  object
 3   Person > Brand              118521 non-null  object
 4   Location                    118521 non-null  object
 5   Project                     118521 non-null  object
 6   Bid Link                    68242 non-null   object
 7   Task                        57197 non-null   object
 8   Type                        118521 non-null  object
 9   Department                  118521 non-null  object
 10  Step                        58058 non-null   object
 11  Date                        118521 non-null  datetime64[ns]
 12  Logged Hours                118521 non-null  float64
 13  Start Time                  118521 non-null  object
 14  Stop Time                   118521 non-null  object
 15  Pay Period                  115198 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(13)
memory usage: 15.4+ MB

#### `Start Time` and `Stop Time` Columns

In [168]:
print(copy_combined_time_logs['Start Time'].apply(type).value_counts())
print(copy_combined_time_logs['Stop Time'].apply(type).value_counts())

Start Time
<class 'str'>    118521
Name: count, dtype: int64
Stop Time
<class 'str'>    118521
Name: count, dtype: int64

In [167]:
copy_combined_time_logs.head(10)[[ 'Start Time', 'Stop Time']]

         Start Time         Stop Time
0  04/09/2024 14:00  04/09/2024 16:00
1  04/11/2024 14:00  04/11/2024 16:00
2  04/10/2024 14:00  04/10/2024 16:00
3  04/02/2024 14:00  04/02/2024 17:00
4  04/02/2024 10:00  04/02/2024 12:00
5  04/02/2024 14:00  04/02/2024 16:30
6  04/03/2024 10:00  04/03/2024 13:00
7  04/02/2024 16:30  04/02/2024 19:00
8  04/04/2024 10:00  04/04/2024 12:00
9  04/03/2024 14:00  04/03/2024 19:00

From the output above, its clear the format is mm/d/y. Splitting the columns and perfroming a review of the output to confirm all the dates are as per the assumption.

In [166]:
print(copy_combined_time_logs['Start Time'].apply(type).value_counts())
print(copy_combined_time_logs['Stop Time'].apply(type).value_counts())

Start Time
<class 'str'>    118521
Name: count, dtype: int64
Stop Time
<class 'str'>    118521
Name: count, dtype: int64